name: "units-test"
on:
  pull_request:
    branches:
      - main
      - master
    types: [closed]

jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
